version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-build-deploy-dev:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP_DEV "~/Code_Spell/Frontend/deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-build-deploy-dev:
          filters:
            branches:
              only:
                - develop

